---
- name: Install Docker and Nmap
  hosts: node2
  become: true  # Run tasks as sudo

  tasks:

    - name: Download and install Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_machine }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        state: started

    - name: Log in to Docker Hub
      community.general.docker_login:
        username: ibrahim1212
        password: 46487087Kk1$
        registry_url: https://index.docker.io/v1/

    - name: Copy HTML/CSS files to Node-2
      ansible.builtin.copy:
        src: /home/ec2-user/myproject/docker
        dest: /home/ec2-user/myproject

    - name: Start Docker Compose
      ansible.builtin.command: 
        cmd: "docker-compose -f /home/ec2-user/myproject/docker/docker-compose.yml up -d --build"

    - name: Push to Docker Hub
      ansible.builtin.command:
        cmd: "docker-compose -f /home/ec2-user/myproject/docker/docker-compose.yml push"

